### ISSUE TITLE
status-url / Icon

### ISSUE THREAD

**Issue by michis0806** [EricConnerApps/homebridge-httpdoor#3]
Hi, I have a strange behavior of the Homekit-icon in ios10. The Icon shows an open garage but it tells me that it's closed...

My Status-URL returns a json with {"state":"closed"}/{"state":"open"}. 

Is this right? Has the Control-URL to return something?

Thanks
Michael

**Comment by eaconner** [comment]
This could be an issue with iOS 10, since it is still a beta I'm not ready to start making changes to support it yet. The Status-URL should return a json string containing `{"state":"closed"}` or `{"state":"open"}`. The Control-URL does not need to return anything.

**Comment by tommyd75** [comment]
I think that is showing a status of YES for "obstruction detected", I'm on iOS 10 as well.
But it's showing closed.
I wonder if theres another status we can add to it to show a NO for "obstruction detected"
